---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config-server
  name: config-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
        visualize: "true"
    spec:
      containers:
      - name: config-server
        image: vanopremudriy/config-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: config-server
spec:
  selector:
    app: config-server
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 8888
  type: NodePort


              