apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-files
  labels:
    app: postgres-files
data:
  POSTGRES_DB: files_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-files
  labels:
    type: local
    app: postgres-files
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-files
  labels:
    app: postgres-files
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-files
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-files
  template:
    metadata:
      labels:
        app: postgres-files
    spec:
      containers:
        - name: postgres-files
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config-files
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim-files

---
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: postgres-files
spec:
  selector:
    app: postgres-files
  ports:
  - name: http
    protocol: TCP
    port: 5432
    targetPort: 5432
  type: NodePort


####################################################


---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: files-service
  name: files-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: files-service
  template:
    metadata:
      labels:
        app: files-service
        visualize: "true"
    spec:
      containers:
      - name: files-service
        image: vanopremudriy/files:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: files-service
spec:
  selector:
    app: files-service
  ports:
  - name: http
    protocol: TCP
    port: 8082
    targetPort: 8082
  type: NodePort