version: '3.9'

services:
  db:
    container_name: files-db
    image: postgres:latest
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: files_db
    ports:
      - "3333:5432"
    volumes:
      - "./db.sql:/docker-entrypoint-initdb.d/db.sql"

  