---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client-service
  name: client-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
        visualize: "true"
    spec:
      containers:
      - name: client-service
        image: vanopremudriy/client:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: client-service
spec:
  selector:
    app: client-service
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
  type: NodePort